version: '3'
services:
  web:
    build: .
    container_name: "omt-project"
    ports:
      - "19000:9000"
    volumes:
      - .:/go/src/omt-project
    env_file:
      - .env_dev
    environment:
      - APP_ENV=DEV
  db:
    image: mysql:5.7
    container_name: "mysql"
    ports:
      - "13306:3306"
    env_file:
      - .env_dev
    environment:
      - APP_ENV=DEV
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
